version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: lawallet_nwc_1
      APP_PORT: 3088
      PROXY_AUTH_ADD: "false"

  postgres:
    container_name: postgres_lawallet_core
    image: postgres:15
    restart: always
    environment:
      DATABASE_HOST: localhost
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: lawallet-nwc
    ports:
      - 5432:5432
    volumes:
      - "${APP_DATA_DIR}/data/postgres:/data"

  app:
    image: masize/lawallet-nwc:0.5.1
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://root:root@postgres/lawallet-nwc"
    depends_on:
      - postgres
    restart: "on-failure"
    stop_grace_period: "1m"
    init: true
