version: "3.8"

services:
  app_proxy:
    environment:
      APP_HOST: lawallet_lightning_1
      APP_PORT: 4988
      PROXY_AUTH_ADD: "false"

  cache:
    container_name: cache_lawallet_lightning
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - cache:/data

  app:
    image: masize/lawallet-lightning:latest
    environment:
      NODE_ENV: production
      REDIS_URI: redis://cache:6379
      PORT: 4988
      NOSTR_RELAYS: "ws://localhost:4848"
    restart: "on-failure"
    stop_grace_period: "1m"
    init: true
    depends_on:
      - cache
